url: https://jpatak16.github.io

# Site settings
title: Jeremy Patak
email: jeremypatak16@gmail.com
description: "Data Analyst, Data Visualist, and Front-End Developer"

# Build settings
markdown: kramdown
permalink: pretty