url: https://jpatak16.github.io

# Site settings
title: Jeremy Patak
email: jeremypatak16@gmail.com
description: "Data Professional: Analysis, Visualization, and Engineering"

# Build settings
markdown: kramdown
permalink: pretty